// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SoftDesign.API.Domain.Models;

[Table("Livro")]
public partial class Livro
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("titulo")]
    [StringLength(50)]
    public string Titulo { get; set; }
    
    [Column("autor")]
    [StringLength(50)]
    public string Autor { get; set; }
    
    [Column("ano_lancamento")]
    public DateOnly AnoLancamento { get; set; }

    [Column("capa")]
    [StringLength(250)]
    public string? Capa { get; set; }

    public Livro(string autor, string titulo, DateOnly ano, string capa)
    {
        this.Autor = autor;
        this.Titulo = titulo;
        this.AnoLancamento = ano;
        this.Capa = capa;
    }

    public Livro()
    {
        
    }
}